import { StyleSheet } from 'react-native';

export const createTasksStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
    zIndex: 0,
  },
  scrollView: {
    flex: 1,
    zIndex: 5,
  },
  header: {
    padding: 20,
    paddingTop: 20,
    alignItems: 'center',
 },
  title: {
    fontSize: 24,
    fontWeight: '1000',
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: 'CabinSketch-Bold',
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    fontFamily: 'CabinSketch-Regular',
  },
  addTaskButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    marginHorizontal: 20,
    marginBottom: 24,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    height: 48,
  },
  addTaskText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'ComicNeue-Regular',
  },
  taskSection: {
    marginHorizontal: 20,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '1000',
    color: colors.text,
    marginBottom: 12,
    fontFamily: 'CabinSketch-Regular',
  },
  taskContainer: {
    flexDirection: 'row',
    alignItems: 'center', 
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: '#cccccc',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    opacity: 0.75,
  },
  completedTaskContainer: {
    backgroundColor: colors.surface,
    opacity: 0.5,
  },
  
  taskContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    marginLeft: 8,
    
    // gap: 8, // gap не поддерживается официально в RN, убери!
  },
  deleteButtonInline: {
    padding: 4,
    alignItems: 'center',
    // marginRight: 28, // у кнопки действия не нужно!
  },
  taskText: {
    fontSize: 16,
    color: colors.text,
    lineHeight: 22,
    marginBottom: 4,
    fontFamily: 'ComicNeue-Regular',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  taskTextCompleted: {
    textDecorationLine: 'line-through',
    color: colors.textSecondary,
  },
  dueDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  dueDateText: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.textSecondary,
    fontFamily: 'ComicNeue-Regular',
    alignItems: 'center',
    marginBottom: 16,
  },
  listDateText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: 'ComicNeue-Regular',
    alignItems: 'center',
    marginLeft: 4, 
  },
  overdue: {
    color: '#EF4444',
    fontWeight: '600',
  },
  dueToday: {
    color: '#F59E0B',
    fontWeight: '600',
  },
  completedDueDate: {
    color: colors.textSecondary,
  },
  taskActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    padding: 4,
    alignItems: 'center',
  },
  emptyState: {
    alignItems: 'center',
    marginTop: 60,
    paddingHorizontal: 40,
  },
  emptyStateText: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 8,
    fontFamily: 'CabinSketch-Regular',
  },
  emptyStateSubtext: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: 'ComicNeue-Regular',
  },
  modalOverlay: {
   flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '1000',
    color: colors.text,
    marginBottom: 16,
    textAlign: 'center',
    fontFamily: 'CabinSketch-Regular',
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 16,
    minHeight: 60,
    textAlignVertical: 'top',
    fontFamily: 'ComicNeue-Regular',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#F3F4F6',
    marginRight: 8,
  },
  saveButton: {
    backgroundColor: colors.primary,
    marginLeft: 8,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: `#6B7280`,
    fontFamily: 'ComicNeue-Regular',
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'ComicNeue-Regular',
  },
});