import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export const createTodayStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
    zIndex: 0,
    
  },
  scrollView: {
    flex: 1,
    zIndex: 5,
    
  },
  header: {
    padding: 20,
    paddingTop: 20,
    alignItems: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: '500',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: 'CabinSketch-Bold',
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    fontFamily: 'CabinSketch-Regular',
  },
  routineSection: {
    marginHorizontal: 20,
    marginBottom: 24,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#cccccc',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    opacity: 0.75,
  },
  routineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  routineTitle: {
    flexDirection: 'row',
    alignItems: 'center',
  
  },
  routineTitleText: {
    fontSize: 20,
    fontWeight: '400',
    marginLeft: 8,
    fontFamily: 'CabinSketch-Regular',
    color: colors.text,
  },
  addButton: {
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.secondary + `30`,
  },
  stepContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  stepText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 22,
    marginLeft: 12,
    color: colors.text,
    fontFamily: 'ComicNeue-Regular',
  },
  stepTextCompleted: {
    textDecorationLine: 'line-through',
    color: colors.textSecondary,
  },
  stepTextDisabled: {
    color: colors.textSecondary + `50`,
  },
  stepActions: {
    flexDirection: 'row',
  },
  actionButton: {
    padding: 8,
    marginLeft: 4,
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  snoozeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    height: 48,
  },
  snoozeText: {
    fontSize: 15,
    color: colors.secondary,
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'ComicNeue-Regular',
  },
  resumeButton: {
    backgroundColor: colors.secondary,
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
  },
  resumeText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: 'ComicNeue-Regular',
  },
  magicalControls: {
    marginBottom: 20,
  },
  addTaskButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginBottom: 12,
    marginHorizontal: 20,
    height: 48,
  },
  addTaskText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'ComicNeue-Regular',
  },
  themeControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  themeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.surface,
    height: 48,
    marginHorizontal: 16,
  },
  themeButtonText: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.text,
    fontFamily: 'ComicNeue-Regular',
  },
  progressSection: {
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#cccccc',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    opacity: 0.75,
  },
  progressTitle: {
    fontSize: 18,
    fontWeight: '1000',
    marginBottom: 16,
    textAlign: 'center',
    color: colors.text,
    fontFamily: 'CabinSketch-Bold',
  },
  progressStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  progressStat: {
    alignItems: 'center',
  },
  progressLabel: {
    fontSize: 13,
    marginBottom: 4,
    color: colors.textSecondary,
    fontFamily: 'ComicNeue-Regular',
  },
  progressValue: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.secondary,
    fontFamily: 'ComicNeue-Bold',
  },
  
  
  closeVictoriesButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignSelf: 'center',
    marginTop: 20,
    height: 48,
    justifyContent: 'center',
  },
  closeVictoriesText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: 'ComicNeue-Regular',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    
  },



  
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '400',
    marginBottom: 16,
    textAlign: 'center',
    color: colors.text,
    fontFamily: 'CabinSketch-Bold',
  },
  textInput: {
    borderWidth: 1,
    borderColor: colors.textSecondary,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.text,
    marginBottom: 20,
    minHeight: 60,
    textAlignVertical: 'top',
    fontFamily: 'ComicNeue-Regular',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#F3F4F6',
    marginRight: 8,
  },
  cancelButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    fontFamily: 'ComicNeue-Regular',
  },
  saveButton: {
    backgroundColor: colors.primary,
    marginLeft: 8,
  },
  saveButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'ComicNeue-Regular',
  },
});